// Example analysis. Shows the prepared brief for the selected scenario and says plainly
// what it is: written in advance, not a live AI call, and not updated by the tasks or
// notes changed in this browser. There is no "generate" button for it.
//
// Below it, "Analyse with Gemini" asks Google's Gemini for a live analysis with the
// viewer's own API key (briefs/gemini.js — the app's only network access). The answer is
// labelled as live AI with its model and time, and its numbers are checked against the
// data before the viewer reads it. There is no fake typing effect.

import { h, t, add } from '../dom.js';
import { pageHead, scopeBar, statusChip } from '../components.js';
import { view, allTasks, businessName, isExcel, scenario, previousScenario, calendarItems } from '../view-state.js';
import { exampleBrief, PROVENANCE } from '../../briefs/examples.js';
import { buildAiPrompt, answerProblems } from '../../briefs/ai-prompt.js';
import { askGemini, looksLikeKey } from '../../briefs/gemini.js';
import { baselineBriefInput } from '../../briefs/brief-facts.js';
import { dayNumber } from '../../data/scenarios.js';
import { formatDate } from '../../core/dates.js';
import { tr, tl, getLocale } from '../../i18n/i18n.js';

export function renderBrief() {
  if (isExcel()) return renderOwnDataBrief(h('div', {}, pageHead(tl('Example analysis')), scopeBar({ period: false })));
  const root = h('div', {}, pageHead(tl('Example analysis'), h('span', { class: 'badge info' }, tr('Prepared in advance · not live AI'))), scopeBar({ period: false }));
  const brief = exampleBrief(view.businessId, view.day, getLocale());
  const n = dayNumber(view.day);
  add(root, h('div', { class: 'banner info' },
    t('p', tr('This is an example analysis written in advance for {0} · Day {1} (reporting date {2}). It was not generated by this page.', businessName(), n, brief ? formatDate(brief.reporting_date) : '—')),
    t('p', tr('It describes the scenario exactly as supplied. It does not re-analyse tasks you accept, complete or re-date here, or the calendar notes you add. For a live analysis of the numbers as they are now, use "Analyse with Gemini" below.'), 'small')));
  if (!brief) add(root, h('div', { class: 'card' }, t('p', tr('No example analysis is prepared for this scenario.'), 'muted')));
  else {
    const tasks = new Map(allTasks().map(x => [x.task_key, x]));
    add(root, h('div', { class: 'card brief' },
      t('h2', brief.headline),
      t('p', brief.summary),
      brief.priorities.length ? h('div', {}, t('h3', tr('Priorities')), h('ol', { class: 'steps' }, ...brief.priorities.map(p => {
        const task = tasks.get(p.task_key);
        return h('li', {}, h('b', {}, task?.title || p.task_key), ` — ${p.why} `, h('i', {}, p.suggested_action),
          task ? h('div', { class: 'small muted' }, tr('In this demo now: '), statusChip(task.status), ' · ', h('a', { href: '#tasks' }, tr('open in Tasks'))) : null);
      }))) : null,
      brief.watch_items.length ? h('div', {}, t('h3', tr('Watch')), h('ul', {}, ...brief.watch_items.map(w => t('li', w)))) : null,
      brief.data_caveats.length ? h('div', {}, t('h3', tr('Data caveats')), h('ul', {}, ...brief.data_caveats.map(w => t('li', w)))) : null));
  }

  add(root, geminiCard());

  if (brief) add(root, h('div', { class: 'card' }, t('h3', tr('How this example was prepared')),
    h('ul', { class: 'small ink2' },
      t('li', tr('Prepared on {0} by Claude, the AI coding assistant used to build this starter — not generated by this page.', formatDate(PROVENANCE.prepared_on))),
      t('li', tr('Written only from the facts below, following the rules in prompts/daily_brief.md.')),
      t('li', tr('An automated test checks every amount, date, count, percentage and record ID in it against the figures this app calculates for this scenario.')),
      t('li', tr('It is a teaching example, not advice about a real business.'))),
    h('details', {}, h('summary', {}, tr('Show the facts it was written from (English, as an AI model would receive them)')),
      h('pre', { class: 'facts' }, baselineBriefInput(view.businessId, view.day, 'en').text))));
  return root;
}

// Your own Excel: no analysis was prepared for it; Gemini can write one on request.
function renderOwnDataBrief(root) {
  add(root, h('div', { class: 'banner info' },
    t('p', tr('No example analysis was prepared for your own data. Nothing is sent anywhere unless you press "Analyse with Gemini" below.'))));
  add(root, geminiCard());
  return root;
}

// The latest live answer per business and day, for this visit only (not saved).
const answers = new Map();
const answerKey = () => `${view.businessId}|${view.day}`;

const PROBLEM_TEXT = {
  key: () => tr('Google did not accept this key. Copy the whole key again from AI Studio, then delete the saved key here and paste the new one.'),
  region: () => tr('Google says the Gemini API is not available where you are.'),
  quota: () => tr('Your free Gemini quota is used up for now. Wait a minute and try again, or try again tomorrow.'),
  busy: () => tr('Gemini is busy right now. Try again in a minute.'),
  model: () => tr('Google could not find a Gemini model for this key. Try again later.'),
  blocked: () => tr('Gemini returned no answer for this request. Try again, or hide the names and try again.'),
  network: () => tr('Could not reach Google. Check your internet connection. (The offline file can analyse only when this computer is online.)'),
  timeout: () => tr('Gemini took too long to answer. Try again.'),
  other: () => tr('Gemini could not answer this time. Try again later.'),
};

// "Analyse with Gemini". Without a saved key: how to get one, and a field to paste it.
// With a key: what will be sent, the button, and the latest answer with its number check.
function geminiCard() {
  const card = h('div', { class: 'card ai-live' });
  const redraw = () => card.replaceWith(geminiCard());
  add(card, t('h3', tr('Analyse with Gemini (live AI)')));
  const key = view.store.geminiKey();

  if (!key) {
    const input = h('input', { type: 'password', autocomplete: 'off', spellcheck: 'false', class: 'key-input', 'aria-label': tr('Gemini API key'), placeholder: tr('Paste your Gemini API key') });
    const status = h('p', { class: 'small', role: 'status', 'aria-live': 'polite' });
    const save = () => {
      const value = input.value.trim();
      if (!looksLikeKey(value)) { status.textContent = tr('That does not look like an API key. Copy the whole key from AI Studio and paste it here.'); return; }
      if (!view.store.setGeminiKey(value)) { status.textContent = tr('This browser does not allow saving, so the key cannot be kept here.'); return; }
      redraw();
    };
    add(card,
      t('p', tr('Gemini can write an analysis of the numbers on this page as they are now. You need your own free Gemini API key from Google AI Studio:'), 'small ink2'),
      h('ol', { class: 'small ink2' },
        t('li', tr('Open aistudio.google.com/apikey and sign in with a Google account.')),
        t('li', tr('Copy your key (if there is none, press Create API key).')),
        t('li', tr('Paste it here and press "Save key".'))),
      h('div', { class: 'row' }, input, h('button', { type: 'button', class: 'btn primary', onclick: save }, tl('Save key'))),
      status,
      t('p', tr('The key is kept only in this browser and is sent only to Google, with your own requests. Treat it like a password: never put it in GitHub (not even as a repository variable) and never share a screenshot of it.'), 'small muted'));
    return card;
  }

  let hide = isExcel(); // your own data: names hidden unless you untick
  const request = () => buildAiPrompt({ scenario: scenario(), previous: previousScenario(), tasks: allTasks(), calendar: calendarItems(), locale: getLocale(), hideNames: hide });
  const preview = h('pre', { class: 'facts ai-request' }, request());
  const status = h('p', { class: 'small', role: 'status', 'aria-live': 'polite' });
  const result = h('div', { class: 'ai-answer-slot' });
  const showAnswer = a => { result.textContent = ''; if (a) add(result, answerView(a)); };
  const button = h('button', { type: 'button', class: 'btn primary', onclick: analyse }, tl('Analyse with Gemini'));

  async function analyse() {
    const prompt = request();
    preview.textContent = prompt;
    const inputs = { scenario: scenario(), previous: previousScenario(), tasks: allTasks(), calendar: calendarItems() };
    const where = `${businessName()}${isExcel() ? '' : ` · ${tr('Day {0}', dayNumber(view.day))}`}`;
    button.disabled = true;
    status.textContent = tr('Waiting for Gemini… (usually 10–30 seconds)');
    const reply = await askGemini({ prompt, key: view.store.geminiKey() });
    button.disabled = false;
    if (!reply.ok) { status.textContent = PROBLEM_TEXT[reply.kind]?.() || PROBLEM_TEXT.other(); return; }
    status.textContent = '';
    const a = { text: reply.text, model: reply.model, at: new Date().toLocaleString(getLocale()), where, problems: answerProblems(reply.text, inputs) };
    answers.set(answerKey(), a);
    showAnswer(a);
  }

  const last4 = key.slice(-4);
  add(card,
    h('div', { class: 'row small' }, t('span', tr('Your key is saved in this browser (ending …{0}).', last4), 'ink2'),
      h('button', { type: 'button', class: 'btn small ghost', onclick: () => { view.store.forgetGeminiKey(); answers.clear(); redraw(); } }, tl('Delete key'))),
    h('label', { class: 'small' }, h('input', { type: 'checkbox', checked: hide, onchange: e => { hide = e.target.checked; preview.textContent = request(); } }), ' ', tr('Replace customer and staff names with codes')),
    h('div', { class: 'row' }, button, status),
    h('div', { class: 'banner warning' }, t('p', tr('Pressing the button sends the text under "Show exactly what will be sent" to Google\'s Gemini. On the free plan Google may use it to improve its products, and asks you not to send personal or confidential information. Use practice data, or data you are allowed to share. Notes you typed are sent as written.'), 'small')),
    h('details', {}, h('summary', {}, tr('Show exactly what will be sent')), preview),
    result);
  showAnswer(answers.get(answerKey()));
  return card;
}

function answerView(a) {
  const check = a.problems.length
    ? h('div', { class: 'banner warning' }, t('p', tr('Number check: these are not in your data — trust the dashboard, not the AI: {0}', a.problems.map(p => p.replace(/^(amount|percentage|date|month|number|unknown record) /, '')).slice(0, 12).join(', ')), 'small'))
    : h('div', { class: 'banner info' }, t('p', tr('Number check: every amount, date, count and record ID in this answer is in your data.'), 'small'));
  return h('div', { class: 'ai-answer' },
    h('p', { class: 'small muted' }, h('span', { class: 'badge info' }, tr('Live AI')), ' ', tr('{0} · {1} · from the figures for {2}', a.model, a.at, a.where)),
    h('div', { class: 'answer-text' }, a.text),
    check,
    t('p', tr('Written by AI: it can be wrong or miss context. It is not professional advice.'), 'small muted'));
}
