// Example analysis. Shows the prepared brief for the selected scenario and says
// plainly what it is: written in advance, not a live AI call, and not updated by the
// tasks or notes changed in this browser. There is deliberately no "generate" button.

import { h, t, add } from '../dom.js';
import { pageHead, scopeBar, statusChip } from '../components.js';
import { view, allTasks, businessName } from '../view-state.js';
import { exampleBrief, PROVENANCE } from '../../briefs/examples.js';
import { baselineBriefInput } from '../../briefs/brief-facts.js';
import { dayNumber } from '../../data/scenarios.js';
import { formatDate } from '../../core/dates.js';
import { tr, tl, getLocale } from '../../i18n/i18n.js';

export function renderBrief() {
  const root = h('div', {}, pageHead(tl('Example analysis'), h('span', { class: 'badge info' }, tr('Prepared in advance · not live AI'))), scopeBar({ period: false }));
  const brief = exampleBrief(view.businessId, view.day, getLocale());
  const n = dayNumber(view.day);
  add(root, h('div', { class: 'banner info' },
    t('p', tr('This is an example analysis written in advance for {0} · Day {1} (reporting date {2}). Nothing on this page contacts an AI service.', businessName(), n, brief ? formatDate(brief.reporting_date) : '—')),
    t('p', tr('It describes the scenario exactly as supplied. It does not re-analyse tasks you accept, complete or re-date here, or the calendar notes you add.'), 'small')));
  if (!brief) { add(root, h('div', { class: 'card' }, t('p', tr('No example analysis is prepared for this scenario.'), 'muted'))); return root; }

  const tasks = new Map(allTasks().map(x => [x.task_key, x]));
  add(root, h('div', { class: 'card brief' },
    t('h2', brief.headline),
    t('p', brief.summary),
    brief.priorities.length ? h('div', {}, t('h3', tr('Priorities')), h('ol', { class: 'steps' }, ...brief.priorities.map(p => {
      const task = tasks.get(p.task_key);
      return h('li', {}, h('b', {}, task?.title || p.task_key), ` — ${p.why} `, h('i', {}, p.suggested_action),
        task ? h('div', { class: 'small muted' }, tr('In this demo now: '), statusChip(task.status), ' · ', h('a', { href: '#tasks' }, tr('open in Tasks'))) : null);
    }))) : null,
    brief.watch_items.length ? h('div', {}, t('h3', tr('Watch')), h('ul', {}, ...brief.watch_items.map(w => t('li', w)))) : null,
    brief.data_caveats.length ? h('div', {}, t('h3', tr('Data caveats')), h('ul', {}, ...brief.data_caveats.map(w => t('li', w)))) : null));

  add(root, h('div', { class: 'card' }, t('h3', tr('How this example was prepared')),
    h('ul', { class: 'small ink2' },
      t('li', tr('Prepared on {0} by Claude, the AI coding assistant used to build this starter — not generated by this page.', formatDate(PROVENANCE.prepared_on))),
      t('li', tr('Written only from the facts below, following the rules in prompts/daily_brief.md.')),
      t('li', tr('An automated test checks every amount, date, count, percentage and record ID in it against the figures this app calculates for this scenario.')),
      t('li', tr('It is a teaching example, not advice about a real business.'))),
    h('details', {}, h('summary', {}, tr('Show the facts it was written from (English, as an AI model would receive them)')),
      h('pre', { class: 'facts' }, baselineBriefInput(view.businessId, view.day, 'en').text))));

  add(root, h('div', { class: 'card' }, t('h3', tr('Adding live AI later')),
    t('p', tr('A live version would send facts like these, plus prompts/daily_brief.md, to an AI service from a small server you control, and check the answer the same way before showing it. The API key must stay on that server — never put it in this page. See docs/STUDENT_SOP.md.'), 'small ink2')));
  return root;
}
