// Packs the training data in data/ into one JavaScript module the app imports:
// src/data/datasets.generated.js. The browser then needs no fetch() and no server,
// so the same code runs from the dev server, in the tests and in the single-file build.
//
// Only business.json, metadata.json and the four CSV files of each day are packed.
// expected_metrics.json answer keys live in test/expected/ and are never packed.
// The Excel templates in data/templates/ are packed separately (as base64) into
// src/data/templates.generated.js so the offline page can offer them for download.
//
// Usage: node scripts/pack-data.js          (writes both modules)
//        node scripts/pack-data.js --check  (exit 1 if either module is out of date)

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
export const DATA_DIR = path.join(root, 'data');
export const OUTPUT = path.join(root, 'src/data/datasets.generated.js');
export const TEMPLATES_DIR = path.join(DATA_DIR, 'templates');
export const TEMPLATES_OUTPUT = path.join(root, 'src/data/templates.generated.js');
const DAYS = ['day1', 'day2'];

export function collectDatasets(dataDir = DATA_DIR) {
  const datasets = {};
  // A business is a folder with a business.json (data/templates/ is not one).
  const businesses = readdirSync(dataDir, { withFileTypes: true }).filter(d => d.isDirectory() && existsSync(path.join(dataDir, d.name, 'business.json'))).map(d => d.name).sort();
  for (const id of businesses) {
    const dir = path.join(dataDir, id);
    const profile = JSON.parse(readFileSync(path.join(dir, 'business.json'), 'utf8'));
    if (profile.id !== id) throw new Error(`${id}/business.json: "id" must be "${id}"`);
    const days = {};
    for (const day of DAYS) {
      const dayDir = path.join(dir, day);
      if (!existsSync(dayDir)) throw new Error(`${id}: missing ${day}/ folder`);
      const metadata = JSON.parse(readFileSync(path.join(dayDir, 'metadata.json'), 'utf8'));
      if (!/^\d{4}-\d{2}-\d{2}$/.test(metadata.as_of_date || '')) throw new Error(`${id}/${day}/metadata.json: as_of_date must be YYYY-MM-DD`);
      const files = {};
      for (const table of profile.tables) files[table.file] = readFileSync(path.join(dayDir, table.file), 'utf8');
      days[day] = { metadata, files };
    }
    datasets[id] = { profile, days };
  }
  // Menu order: the "order" field in business.json, then folder name.
  const sorted = Object.entries(datasets).sort(([a, x], [b, y]) => (x.profile.order ?? 99) - (y.profile.order ?? 99) || a.localeCompare(b));
  return Object.fromEntries(sorted);
}

export function renderModule(datasets) {
  return [
    '// GENERATED by scripts/pack-data.js from the data/ folder. Do not edit by hand:',
    '// change the files in data/ and run `npm run data` (dev, build and test do it too).',
    '// All records are synthetic BetterSpace training data.',
    `export const DATASETS = ${JSON.stringify(datasets, null, 1)};`,
    '',
  ].join('\n');
}

// The Excel templates (the training workbooks), as base64, in file-name order.
export function renderTemplatesModule(dir = TEMPLATES_DIR) {
  const files = existsSync(dir) ? readdirSync(dir).filter(f => f.toLowerCase().endsWith('.xlsx')).sort() : [];
  const templates = files.map(file => ({ file, base64: readFileSync(path.join(dir, file)).toString('base64') }));
  return [
    '// GENERATED by scripts/pack-data.js from data/templates/*.xlsx. Do not edit by hand.',
    '// The training workbooks, offered as Excel templates on the "My Excel" page.',
    `export const TEMPLATES = ${JSON.stringify(templates, null, 1)};`,
    '',
  ].join('\n');
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const datasets = collectDatasets();
  const outputs = [[OUTPUT, renderModule(datasets)], [TEMPLATES_OUTPUT, renderTemplatesModule()]];
  if (process.argv.includes('--check')) {
    const stale = outputs.filter(([file, text]) => !existsSync(file) || readFileSync(file, 'utf8') !== text);
    if (stale.length) { console.error(`Out of date: ${stale.map(([f]) => path.relative(root, f)).join(', ')}. Run: npm run data`); process.exit(1); }
    console.log('Packed data is up to date.');
  } else {
    for (const [file, text] of outputs) writeFileSync(file, text);
    console.log(`Packed ${Object.keys(datasets).join(', ')} and ${outputs[1][1].match(/"file"/g)?.length || 0} Excel template(s) into src/data/`);
  }
}
