// Packs the training data in data/ into one JavaScript module the app imports:
// src/data/datasets.generated.js. The browser then needs no fetch() and no server,
// so the same code runs from the dev server, in the tests and in the single-file build.
//
// Only business.json, metadata.json and the four CSV files of each day are packed.
// expected_metrics.json answer keys live in test/expected/ and are never packed.
//
// Usage: node scripts/pack-data.js          (writes the module)
//        node scripts/pack-data.js --check  (exit 1 if the module is out of date)

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
export const DATA_DIR = path.join(root, 'data');
export const OUTPUT = path.join(root, 'src/data/datasets.generated.js');
const DAYS = ['day1', 'day2'];

export function collectDatasets(dataDir = DATA_DIR) {
  const datasets = {};
  const businesses = readdirSync(dataDir, { withFileTypes: true }).filter(d => d.isDirectory()).map(d => d.name).sort();
  for (const id of businesses) {
    const dir = path.join(dataDir, id);
    const profile = JSON.parse(readFileSync(path.join(dir, 'business.json'), 'utf8'));
    if (profile.id !== id) throw new Error(`${id}/business.json: "id" must be "${id}"`);
    const days = {};
    for (const day of DAYS) {
      const dayDir = path.join(dir, day);
      if (!existsSync(dayDir)) throw new Error(`${id}: missing ${day}/ folder`);
      const metadata = JSON.parse(readFileSync(path.join(dayDir, 'metadata.json'), 'utf8'));
      if (!/^\d{4}-\d{2}-\d{2}$/.test(metadata.as_of_date || '')) throw new Error(`${id}/${day}/metadata.json: as_of_date must be YYYY-MM-DD`);
      const files = {};
      for (const table of profile.tables) files[table.file] = readFileSync(path.join(dayDir, table.file), 'utf8');
      days[day] = { metadata, files };
    }
    datasets[id] = { profile, days };
  }
  // Menu order: the "order" field in business.json, then folder name.
  const sorted = Object.entries(datasets).sort(([a, x], [b, y]) => (x.profile.order ?? 99) - (y.profile.order ?? 99) || a.localeCompare(b));
  return Object.fromEntries(sorted);
}

export function renderModule(datasets) {
  return [
    '// GENERATED by scripts/pack-data.js from the data/ folder. Do not edit by hand:',
    '// change the files in data/ and run `npm run data` (dev, build and test do it too).',
    '// All records are synthetic BetterSpace training data.',
    `export const DATASETS = ${JSON.stringify(datasets, null, 1)};`,
    '',
  ].join('\n');
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const datasets = collectDatasets();
  const text = renderModule(datasets);
  if (process.argv.includes('--check')) {
    const current = existsSync(OUTPUT) ? readFileSync(OUTPUT, 'utf8') : '';
    if (current !== text) { console.error('src/data/datasets.generated.js is out of date. Run: npm run data'); process.exit(1); }
    console.log('Packed data is up to date.');
  } else {
    writeFileSync(OUTPUT, text);
    console.log(`Packed ${Object.keys(datasets).join(', ')} into ${path.relative(root, OUTPUT)}`);
  }
}
