// Settings for a published copy of this site. Students do not edit this file: they set a
// GitHub repository variable (Settings → Secrets and variables → Actions → Variables), and
// the build fills it in here (scripts/site-config.js checks it first):
//
//   BUSINESS_NAME  the business name shown at the top (e.g. 小明家具店); without it, the
//                  name of the opened Excel file is shown
//
// The empty value below is what the classroom file uses. npm run dev also reads the
// variable from the environment.
export const SITE_CONFIG = Object.freeze({ businessName: '' });
