// Settings for a published copy of this site. Students do not edit this file: they set
// GitHub repository variables (Settings → Secrets and variables → Actions → Variables),
// and the build fills them in here (scripts/site-config.js checks them first):
//
//   BUSINESS_NAME  the name shown for "My Excel", their own workbook (e.g. 小明家具店)
//   START_WITH     which business opens first: my-excel, b2c or b2b
//
// The empty values below are what the classroom file uses. npm run dev also reads the
// two variables from the environment.
export const SITE_CONFIG = Object.freeze({ businessName: '', startWith: '' });
